### ISSUE TITLE
plugin name mismatch

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [scalameta/paradise#105]
1) **macroparadise**:
https://github.com/scalameta/paradise/blob/master/plugin/src/main/scala/org/scalameta/paradise/Plugin.scala#L17

vs:

2) **meta-paradise-plugin** (jar/scalac-plugin.xml)
http://search.maven.org/#artifactdetails%7Corg.scalameta%7Cparadise_2.11.8%7C3.0.0-M5%7Cjar

problem in scala-ide 4.4.1:
- `Xplugin-require` needs `macroparadise` to discover from `Xpluginsdir` jars
- `meta-paradise-plugin` does not work

**Comment by xeno-by** [comment]
@olafurpg Can you take a look at this please?

**Comment by olafurpg** [comment]
I think we can make the two the same

Here: https://github.com/scalameta/paradise/blob/280a8762c661d8be7782e7ec8c2f87a6d29b4afe/plugin/src/main/scala/org/scalameta/paradise/embedded/scalac-plugin.xml#L2
and here: https://github.com/scalameta/paradise/blob/280a8762c661d8be7782e7ec8c2f87a6d29b4afe/plugin/src/main/scala/org/scalameta/paradise/Plugin.scala#L17

Which one do you prefer @xeno-by, `meta-paradise-plugin` or `macroparadise`? I think `meta-paradise-plugin` is better.

**Comment by DavidDudson** [comment]
I think meta paradise is more consistent

**Comment by xeno-by** [comment]
This is strange. These two names are different in macro paradise 2.x, too:
* https://github.com/scalamacros/paradise/blob/2.11.8/plugin/src/main/scala/org/scalamacros/paradise/embedded/scalac-plugin.xml#L2
* https://github.com/scalamacros/paradise/blob/2.11.8/plugin/src/main/scala/org/scalamacros/paradise/Plugin.scala#L11

I'll debug this one of these days and figure this out definitively.

I think, we'll need to keep `macroparadise` in order to retain backward compatibility with macro paradise 2.x. After all, 3.x and 4.x not only support new macro annotations, but also support old macro annotations.

**Comment by xeno-by** [comment]
I've briefly taken a look at the place inside the Scala compiler where compiler plugins are loaded. It seems that the `<name>` from `scalac-plugin.xml` only affects error messages, so we can put anything we want there. 

I suggest we maintain backward compatibility, and use whatever macro paradise 2.x is using, i.e. `macro-paradise-plugin`.

@Andrei-Pozolotin What kind of problems are you encountering? `-Xplugin-require:macroparadise` works for me. I guess, there's some problem specific to Scala IDE?

**Comment by Andrei-Pozolotin** [comment]
@xeno-by 

the problem is "confusion": 

1) here: https://github.com/scalameta/paradise/blob/master/README.md
you say `-Xplugin:<paradise>`, which prompts for search for "what you mean by `<paradise>`"?

2) the search results in 2 names:
* `macroparadise`
* `meta-paradise-plugin`

3) since I want `meta` and not `macro`, 
* I choose `meta-paradise-plugin`, 
* and that does not work :-)

so, it would help to:
* clarify and verify your examples
* use single consistent naming throughout

thank you

**Comment by Andrei-Pozolotin** [comment]
probably should clarify: we do not use `-Xplugin`. instead, we collect all plugins jars in a single directory `Xpluginsdir` and then load them by plugin names via `Xplugin-require`:

![image](https://cloud.githubusercontent.com/assets/1622151/19948566/200d9f48-a11b-11e6-88a6-b22d2bdfba7c.png)

**Comment by xeno-by** [comment]
It is unfortunate that we use two different names in scalac-plugin.xml and in Plugin.scala, but I'm not sure whether we can change that at this point. I think we should provide clear instructions instead, so that noone has to grep the source code in the first place.

Using @olafurpg's excellent template project for new-style macro annotations, I created a tutorial that explains writing such macros and goes through environment setup instructions: https://github.com/xeno-by/tutorial/tree/macros. @Andrei-Pozolotin, would you have time to contribute to the Eclipse section of the tutorial?
