### ISSUE TITLE
Annotation expansion cannot have arguments

### ISSUE THREAD

**Issue by yilinwei** [scalameta/paradise#11]
If you try adding arguments in the annotation it fails with `exception during macro expansion, wrong number of arguments`. The `$mods` extracted in the quasiquote also does not have the expansion `@annotation` inside.

I'm assuming that I should be digging around in `Expanders.scala`?

**Comment by iTakeshi** [comment]
Do you mean that the problem is `@macroAnnotation(arg) object Foo` fails?

**Comment by xeno-by** [comment]
I'd like the following code example to work:

```
import scala.meta._

class main(greeting: String) extends scala.annotation.StaticAnnotation {
  inline def apply(defn: Any) = meta {
    val q"object $name { ..$stats }" = defn
    val main = q"""
      def main(args: Array[String]): Unit = {
        println($greeting)
        ..$stats
      }
    """
    q"object $name { $main }"
  }
}
```

```
@main("hello world")
object Test {
  println("bye-bye world")
}
```

For that I think that the following will need to be done:
  - [ ] Change the meta block compilation scheme to make it closer to [the pre-SIP](https://github.com/scala/scala.github.com/pull/530/files#diff-b8202bb65ece90a61f39ae56c28ee1feR139). I doubt that it will be easy to implement the entirety of the pre-SIP, but just allowing type and term arguments for annotations should be a big step forward. Here's how inline and meta are compiled right now: https://github.com/scalameta/paradise/blob/9c40786557fa8d86cfc9eb40252c3cce5df7a2ca/plugin/src/main/scala/org/scalamacros/paradise/parser/SyntaxAnalyzer.scala#L121.
  - [ ] Make sure that `expandNewAnnotationMacro` correctly passes annotation arguments to the synthetic method that it executes.

**Comment by iTakeshi** [comment]
Thanks for comprehensive example and description. I'll tackle it, but it will take a little bit longer, I think.

**Comment by xeno-by** [comment]
Sounds great! Please let me know if you have further questions.

**Comment by DavidDudson** [comment]
Extremely keen for this functionality. Required for any boilerplate free work on https://github.com/DavidDudson/InlineMacros

**Comment by iTakeshi** [comment]
@xeno-by sorry for late response (occupied with another project last week)

I tried the test case you showed above, and encount an error which says `not found: value greeting` (at `println($greeting)` in the quasiquote interpolation).

The macro implementatin
```scala
class main(greeting: String) extends scala.annotation.StaticAnnotation {
  inline def apply(defn: Any) = meta {
    val q"object $name { ..$stats }" = defn
    val main = q"""
      def main(args: Array[String]): Unit = {
        println($greeting)
        ..$stats
      }
    """
    q"object $name { $main }"
  }
}
```
is translated by syntax analyzer (https://github.com/scalameta/paradise/blob/2.11.8/plugin/src/main/scala/org/scalamacros/paradise/parser/SyntaxAnalyzer.scala#L121) into
```scala
class main(greeting: String) extends scala.annotation.StaticAnnotation {
  @new scala.meta.internal.inline.inlin() def apply(defn: Any) = ???
}
object main$impl {
  def apply(defn: Any) = {
    val q"object $name { ..$stats }" = defn
    val main = q"""
      def main(args: Array[String]): Unit = {
        println($greeting)
        ..$stats
      }
    """
    q"object $name { $main }"
  }
}
```
Because of this translation, the macro implementation ignores the constructor arguments of the annotation class.

Questions:
* Why do we have to move the `apply` into the companion? Why can't we handle the macro expansion in the class?
* If the `apply` should be in the companion, the simplest solution I think is currying it within the translation phase like `def apply(greeting: String)(defn: Any)`. Do you have any other ideas?

**Comment by xeno-by** [comment]
That's a very comprehensive analysis! I'll try to respond with details soon.

**Comment by xeno-by** [comment]
1) `apply` should be a member of the companion, because it needs to be invokable at compile-time. If we declare `apply` in the class, then we won't be able to reflectively instantiate it during macro expansion. 

E.g. if we have `object x; @foo(x) class C`, then we clearly can't create an instance of `foo` at compile time, because it refers to a value of an object that hasn't been compiled yet.

This shows a fundamental peculiarity of meta blocks. Even though sometimes you may think that you see something in lexical scope, you actually don't, just like in this situation with `greetings`.

2) Indeed, we could encode macro annotation expansion as you propose, requiring methods to take two parameter lists - one for arguments of annotations and one for the definitions. I did exactly that during 3.0.0-M1 that powered my ScalaDays NYC demo.

However, that would violate the intuition that annotations on definitions can be thought of as constructor calls of the associated class, and that'd be inconsistent with existing usages of annotations in Scala. I remember that, when we chatted after my ScalaDays presentation, Martin Odersky didn't like this approach.

=======

Clearly, this represents a design conundrum. On the one hand, we'd like `greetings` to be available in the meta scope, but, on the other hand, I don't really see how we can pull this off with the current limitations.

What I suggest is that we give up on accessing `greetings` directly inside the body, and instead require metaprogrammers to explicitly write `val q"new $_($greetings)" = this`.

What does this mean? Let me explain.

As you have seen, meta blocks do weird things with variables from lexical scope. For example, they turn inline method parameters from variables of type `T` to variables of type `scala.meta.Tree` and subclasses thereof.

What I propose is that we give `this` special meaning as well. Concretely, inside meta blocks, `this` should represent the prefix of the inline method call that we're currently expanding.

For example, we encode `@foo class X` as `new foo().apply(q"class X")`. In this synthetic expression, the prefix is `new foo()`, which means that `this` will be translated to `q"new foo()"` inside the body of the meta block of the corresponding macro annotation.

What do you think?

=======

In order to implement this design, we'll need the following:
  [ ] Change the translation scheme in SyntaxAnalyzer to create a dedicated parameter for the prefix and then replace all references to `this` with references to that parameter.
  [ ] Fix macro expansion logic, so that it doesn't crash whenever a macro annotation takes an argument (regardless of whether that argument is used or not).

**Comment by iTakeshi** [comment]
1) understood, but maybe I need to study a little more about compilation procedure of scala (if you know good resources (i.e. docs or blog posts or something), plz tell me!). For this case, you mean the member of the companion can be invoked like https://github.com/scalameta/paradise/blob/2.11.8/plugin/src/main/scala/org/scalamacros/paradise/typechecker/Expanders.scala#L131 , but the field of a class can't, right?

2) I checked `3.0.0-M1` source (https://github.com/scalameta/paradise/blob/2.11.8/plugin/src/main/scala/org/scalamacros/paradise/typechecker/Expanders.scala#L131). I guess the cause why you feel gross to be the style in which metaprogrammers define `apply` in the class, say:
```scala
class main extends StaticAnnotation { // at that time it should be an object
  def apply(greeting: String)(defn: Any): Stat = ...
}
@main("hello") object { ... }
```
Actually it is unintuitive that the annotation argument `"hello"` is not a constructor argument. However, given we have to do some translation on the definition in the paradise, we can synthesize curried function using constructor argument, i.e.:
```scala
// metaprogrammers can write like following
class main(greeting: String) extends StaticAnnotation {
  inline def apply(defn: any): Stat = ...
}
@main("hello") object { ... } // "hello" *SEEMS TO BE* a constructor argument

// we can transplant the constructor argument into apply
class main(greeting: String) extends StaticAnnotation {
  @scala.meta.internal.inline.inline() def apply(defn: Any): Stat = ???
}
object main {
  def apply(greeting: String)(defn: Any): Stat = ...
}
```
I have not confirmed it works, but I suppose it does. In this way, metaprogrammers can write in natural and intuitive style, and on the same time we can handle them easily.
What do you think?

3) I got your point, but personally I prefer the way I proposed above in (2), because this increases metaprogrammers' inconvinenience. One possible solution is to generate `val q"new $_($greetings)" = this` automatically just as (2), but if we use this auto-generation strategy, curried function is much simpler.

Any comments will be appreciated! :)

**Comment by DavidDudson** [comment]
I agree, binding parameters to this seems hackish and unusual from a user perspective.

From my perspective, if we can make the Syntax

```
class A(arg) extends StaticAnnotation {
  def apply(defn: Defn) = meta {
    ...
  }
}

 @A(arg)
def something()
```

We should, even if we have to generate the boilerplate of currying in the argument

**Comment by DavidDudson** [comment]
Side note... Does this issue include type arguments? Or is that a seperate issue? (I haven't tried yet so it may even be possible currently).

**Comment by iTakeshi** [comment]
@DavidDudson thanks for your comments! I agree with you that it's worth considering about type parameters in this issue. I'll try to make it possible:
```scala
class main[T](someArg: T) extends StaticAnnotation {
  inline def apply(defn: Any): Stat = ...
}
@main[String]("hello") object Foo {  }
```

**Comment by iTakeshi** [comment]
@xeno-by Related to @DavidDudson 's comment, I have a question. In https://github.com/scalameta/paradise/blob/2.11.8/plugin/src/main/scala/org/scalamacros/paradise/parser/SyntaxAnalyzer.scala#L152 the `implVparamss` is generated by merging with `implVtparamss`, and in `L155` the `tparams` argument of the `DefDef` is explicitly set to `Nil`. Why is such translation needed?

**Comment by DavidDudson** [comment]
Something like `@SpecializeAll[T]` where `T <: AnyVal : TypeTag`

This would generate `@specialized` annotations for all methods on this class, but only of type T 

e.g. `@specialized(typeOf[T])`

But given the complexity of this and how edge case it is, I would ignore it for now and this can be a problem that is fixed later

**Comment by iTakeshi** [comment]
@DavidDudson Thanks for sample use case, but my question was a little bit different (sorry for my misleading comment)

My point is that the type parameter should be attributed to the annotation class, but not to the `apply` method, i.e.
```scala
// should be like this
class main[T](someArg: T) extends StaticAnnotation {
  inline def apply(defn: Any): Stat = ??? // may use [T]
}

// I think this case is not occuring
class main(someArg: String) extends Static Annotation {
  inline def apply[T](defn: Any): Stat = ??? // use [T] in the function body
}
```
Is there any case which requires the second form of definition?

If there isn't, probably we can drop this line https://github.com/scalameta/paradise/blob/2.11.8/plugin/src/main/scala/org/scalamacros/paradise/parser/SyntaxAnalyzer.scala#L151 , and it will be much easier to manipulate the curried parameters.

**Comment by DavidDudson** [comment]
Ah i see. I can't see this being used very often at all. Abstracting over Defn/Decl doesnt seem ideal. What i would suggest doing is create another ticket for that and reference the commit that removes this functionality. That way if anyone does need this, it will get voted on and/or someone will implement it.

**Comment by xeno-by** [comment]
@iTakeshi @DavidDudson Indeed, in the case of macro annotations, `def apply` can't have type parameters. 

On the other hand, if we consider a more general case that involves def macros as described in https://gist.github.com/xeno-by/9d7a709b1ba7c2ee64cfedcc5d264bd5, then inline methods can and will have type parameters.

**Comment by xeno-by** [comment]
Fix proposed in https://github.com/scalameta/paradise/pull/27.

**Comment by iTakeshi** [comment]
@xeno-by Finally I understand why `implVtparamss` is necessary. Thanks for the ref.
Also, I'll see #27 this weekend.
