### ISSUE TITLE
[LogicalTrees] Trait Primary Constructor

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/paradise#21]
As shown in https://github.com/DavidDudson/paradise/commit/2076604266f381826ef8816aaade719ee7c4f2e8 (```sbt test:compile``` fails)

The problem is g.Empty Tree is passed in: https://github.com/scalameta/paradise/blob/2.11.8/plugin/src/main/scala/org/scalamacros/paradise/converters/LogicalTrees.scala#L485

What is the solution to this problem? Do we make Def.Trait's PrimaryCtor Optional in Meta? Or is there some other way to solve this issue?

**Comment by xeno-by** [comment]
@dveim Could you comment on this?

**Comment by Dveim** [comment]
Looks like this issue is fixed in https://github.com/dveim/paradise/commit/1d9a66fa564df312b88bf8b9057b31f1382715ed. Going to make PR soon.

As far as I understand, changing scalameta's API would require big effort. Another solution for such cases with `EmptyTree` -- use some zero analogue for particular tree.

**Comment by DavidDudson** [comment]
@xeno-by can this issue be closed now, If I recall correctly that PR was merged?

**Comment by xeno-by** [comment]
Yes, that's right. Thanks!
